Add docker compose script
noipcom/linux-update-client-docker pull request #1
Opened 2024-09-11 21:32 UTC by dlg1206

Add docker compose script to handle restarting the noip service after reboot

2024-09-27 00:07 UTC, aden-webster commented
Thank you for creating this. It is a simple addition that some people have asked for, so we see no reason not to add a Docker Compose template and snippet to the Readme.

2024-10-02 20:46 UTC, aden-webster requested changes

2024-10-02 20:46 UTC, aden-webster commented on docker-compose.yml
The Docker Compose [standard](https://docs.docker.com/compose/intro/compose-application-model/) has changed to `compose.yaml` as the file name, please update this follow best practices.

2024-10-02 20:46 UTC, aden-webster commented on README.md
> +3b. To restart in the backgorund autmatically, use the docker compose script:
Please add additional context here to introduce Docker Compose.

Such as: 
```
### Docker Compose 

Alternatively, you can use our Docker Compose file included in the repository to restart automatically... 
```

And please check your spelling 😀

2024-10-02 21:46 UTC, dlg1206 commented on README.md
> +3b. To restart in the backgorund autmatically, use the docker compose script:
Sorry about that, made the changes originally on github directly. I've been using noip for years, glad to see there's docker support now! :)

2024-12-08 15:32 UTC, SniperRus commented on README.md
> +3b. To restart in the backgorund autmatically, use the docker compose script:
typo: `autmatically` - should be `automatically`

2025-04-22 17:11 UTC, eleanordoesntcode commented
LGTM

2025-04-27 16:38 UTC, jrasko commented on compose.yaml
> +    restart: always         # will restart after server reset
Hey, consider adding ipv6 support:
```suggestion
    restart: always         # will restart after server reset
    networks:
      - noip_duc
networks:
  noip:
    enable_ipv6: true
```

2025-06-12 21:13 UTC, aden-webster approved these changes
Thank you @dlg1206, @SniperRus  and @jrasko for your work on this.

2025-06-12 21:14 UTC, merged